### ISSUE TITLE
Sensor issue and error preventing boot

### ISSUE THREAD

**Issue by electricalhog** [TG-Techie/TG-Watch-Software#42]
My watch battery was very low last night (3%) and when I plugged it in it shut off. I figured it must have gotten power for a fraction of a second and then lost it again before a solid connection was made and it had shut off. It didn't turn back on but I remembered that it will go into low battery boot if it's below 4% so I didn't worry. After a full night's charge, it would start to boot when reset but would never make it to the splash screen.

Plugging it in revealed that it was experiencing an error:
>code.py output:
resetting touchscreen
initing sensors failed
Traceback (most recent call last):
  File "code.py", line 3, in <module>
  File "hardware/__init__.py", line 6, in <module>
  File "hardware/drivers.py", line 29, in init
  File "hardware/drivers.py", line 132, in init_sensors
  File "hardware/drivers.py", line 132, in init_sensors
  File "hardware/drivers.py", line 122, in init_sensors
  File "adafruit_drv2605.py", line 102, in __init__
  File "adafruit_drv2605.py", line 130, in _read_u8
  File "adafruit_drv2605.py", line 130, in _read_u8
  File "adafruit_bus_device/i2c_device.py", line 143, in write_then_readinto
OSError: [Errno 19] Unsupported operation

I don't know what part of my story is accurate because basically all of it is speculation. The error seems weird to me but fixing it is probably over my head.

**Comment by electricalhog** [comment]
This is the same issue as #38 🤦🏻‍♂️
